### ISSUE TITLE
sequence item 1: expected string or Unicode, bool found

### ISSUE THREAD

**Issue by SaFi2266** [oerp-odoo/service-management#4]
Hi,
While trying install base_location_extension I get the error message below 

```
File "/opt/odoo8/custom/oca/base_location/models/better_zip.py", line 57, in _get_display_name
    self.display_name = ", ".join(name)
ParseError: "sequence item 1: expected string or Unicode, bool found" while parsing /opt/odoo/custom_addons/base_location_extension/demo/demo_addresses.xml:5, near
<record id="demo_address_id_1" model="res.better.zip">
            <field name="name">LT-0251</field>
            <field name="street_id" ref="street_id_1"/>
            <field name="city_id" ref="city_id_1"/>
            <field name="state_id" ref="state_id_9"/>
            <field name="country_id" ref="base.lt"/>
        </record>
```

will you please help me to fix this 

Regards
SaFi

**Comment by oerp-odoo** [comment]
Hello,
the problem is, that my module base_location_extension depends on 
another community module base_location. And that module changed 
functionality how display_name is showed now. It expects 'city' field to 
be entered, because it is required there. And in my module it is not 
required, because 'city_id' field is used instead. To be able to fix it, 
I need to change some parts of the code, so it would follow what changed 
in dependent module. I will fix that when I will have some free time.

On 2016.01.04 21:05, Mustafa J. Kadhem wrote:

> Hi,
> While trying install base_location_extension I get the error message 
> below
> 
> |File "/opt/odoo8/custom/oca/base_location/models/better_zippy", line 
> 57, in _get_display_name selfdisplay_name = ", "join(name) ParseError: 
> "sequence item 1: expected string or Unicode, bool found" while 
> parsing 
> /opt/odoo/custom_addons/base_location_extension/demo/demo_addressesxml:5, 
> near <record id="demo_address_id_1" model="resbetterzip"> <field 
> name="name">LT-0251</field> <field name="street_id" 
> ref="street_id_1"/> <field name="city_id" ref="city_id_1"/> <field 
> name="state_id" ref="state_id_9"/> <field name="country_id" 
> ref="baselt"/> </record> |
> 
> will you please help me to fix this
> 
> Regards
> SaFi
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/boolit-team/service-management/issues/4.

## 

Pagarbiai / Regards

Andrius Laukavičius

Boolit programuotojas / developer

(+370) 52 032 766

dev@boolit.eu mailto:info@oerp.lt

Odoo Partner https://www.odoo.com/partners/NOD-3621

www.oerp.lt http://www.oerp.lt

www.odoolietuva.lt http://www.odoolietuva.lt

**Comment by SaFi2266** [comment]
Hello,

Thank you for your time to write the explanation, 
I will be waiting your free time, and really appreciate your efforts.

Regards
SaFi

**Comment by oerp-odoo** [comment]
Hello,
code was refactored and improved for v8. You can pull latest updates and check. It should be working now.

**Comment by SaFi2266** [comment]
Thank you,
The module installed correctly and works fine
thanks again 
Regards
SaFi
